config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/restaurant'
  get 'pages/dish'
  get 'result' => "pages#result"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def restaurant
  end

  def dish
  end

  def result
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peppame</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/dish.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>Peppa Web</title>
<link href="css/bootstrap.min.css"  type="text/css" rel="stylesheet"/>
<link href="css/bootstrap-theme.min.css" type="text/css" rel="stylesheet" />
<link href="css/bootstrap-theme.min.css.map" type="text/css" rel="stylesheet" />
<link href="css/style.css"  type="text/css" rel="stylesheet"/>
</head>
<body>
	<header id="headr">
		<div class="container-fluid">
			<div class="row">
					<nav class="navbar navbar-default navbar-static-top">
						<div class="navbar-header">
						  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						  </button>
						  <a class="navbar-brand" href="#"><img src="/assets/logo.png"></a>
						</div>
							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							  <ul class="nav navbar-nav left_nav">
								<li class="dropdown">
								  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Collingwood, VIC <span class="caret"></span></a>
								  <ul class="dropdown-menu">
									<li>
									  <form>
										<div class="input-group">
										  <input type="text" class="form-control" placeholder="location">
										  <span class="input-group-btn">
											<button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> </button>
										  </span>
										</div>
									  </form>
									</li>

								  </ul>
								</li>
							  </ul>
							  <ul class="nav navbar-nav navbar-right">
								<li><a href="#"><img src="/assets/nav_button_download.png" <="" a=""></a></li><a href="#">
							  </a></ul>
							</div><!-- /.navbar-collapse -->
					</nav>
				</div>
		</div>
	</header>
	<section id="single_food">
		<div class="container-fluid">
			<div class="row">
				<div class=" col-lg-3 col-md-3 col-sm-12 col-xs-12 no_padding_left no_padding_right">
					<div class="restra_inner">
						<div class="dish_info_left">
							<div class="food_sml_left"><img src="/assets/6.png" alt="restra" /></div>
							<div class="food_sml_right">
								<h2 class="restra_title">Dough Cookies</h2>
								<p class="restra-txt">madam chocolat</p>
							</div>
						</div>
						<div class="review_left">
							<div class="food_sml_left"><img src="/assets/6.png" alt="restra" /></div>
							<div class="food_sml_right">
								<h2 class="rv_txt">This is fantastic! This was so fantastic!</h2>
								<p class="restra-txt">adelaide hudson</p>
							</div>
						</div>
						<div class="review_left">
							<div class="food_sml_left"><img src="/assets/6.png" alt="restra" /></div>
							<div class="food_sml_right">
								<h2 class="rv_txt">This is fantastic! This was so fantastic!</h2>
								<p class="restra-txt">adelaide hudson</p>
							</div>
						</div>
						<div class="review_left">
							<div class="food_sml_left"><img src="/assets/6.png" alt="restra" /></div>
							<div class="food_sml_right">
								<h2 class="rv_txt">This is fantastic! This was so fantastic!</h2>
								<p class="restra-txt">adelaide hudson</p>
							</div>
						</div>
						<div class="review_left">
							<div class="food_sml_left"><img src="/assets/6.png" alt="restra" /></div>
							<div class="food_sml_right">
								<h2 class="rv_txt">This is fantastic! This was so fantastic!</h2>
								<p class="restra-txt">adelaide hudson</p>
							</div>
						</div>
						<div class="review_left">
							<div class="food_sml_left"><img src="/assets/6.png" alt="restra" /></div>
							<div class="food_sml_right">
								<h2 class="rv_txt">This is fantastic! This was so fantastic!</h2>
								<p class="restra-txt">adelaide hudson</p>
							</div>
						</div>

					</div>

				</div>
				<div class=" col-lg-9 col-md-9 col-sm-12 col-xs-12 no_padding_right no_padding_left hover_outr">
					<div class="single_item">
					<figure class="effect-lily">
							<div class="dish_top">
							<img src="/assets/food-single.jpg" alt="single food item" class="dish_bk_img"/>
							<div class="dish_overlay"></div>
							<div class="rating">
										<span>Close</span>
									</div>
							<figcaption>
								<div>
									<h2>Dough cookies</h2>
									<p>Madam Chocolate <span class="rst_price">$15</span></p>
								</div>
							</figcaption>
							</div>
						</figure>
					</div>


				</div>

			</div>
		</div>
	</section>
	<!--<footer id="footr">
          <div class="container">
            <div class="row">
              <div class="col-lg-4 col-md-4 pull-right">
                <img src="/assets/phone.png" class="phone_img">
              </div>
			  <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <h2 class="footr_txt"> Do more with the app. Download it today!</h2>
                <ul>
					<li><a href="#"><img src="/assets/button_google_download.png"></a></li>
					<li><a href="#" class="appbutton"><img src="/assets/button_apple_download.png"></a></li>
				</ul>
              </div>

            </div>
          </div>
        </footer>-->

<script src="js/jquery-1.11.3.js" type="text/javascript" ></script>
<script src="js/custom_js.js" type="text/javascript"></script>
<script src="js/bootstrap.min.js" type="text/javascript" ></script>
<!--footer -->
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>Peppa Web</title>
<link href="css/bootstrap.min.css"  type="text/css" rel="stylesheet"/>
<link href="css/bootstrap-theme.min.css" type="text/css" rel="stylesheet" />
<link href="css/bootstrap-theme.min.css.map" type="text/css" rel="stylesheet" />
<link href="css/style.css"  type="text/css" rel="stylesheet"/>
</head>
<body>
	<header id="headr">
		<div class="container">
			<div class="row">
					<nav class="navbar navbar-default navbar-static-top">
						<div class="navbar-header">
						  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						  </button>
						  <a class="navbar-brand" href="#"><img src="/assets/logo.png"></a>
						</div>
							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							  <ul class="nav navbar-nav left_nav">
								<li class="dropdown">
								  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Collingwood, VIC <span class="caret"></span></a>
								  <ul class="dropdown-menu">
									<li>
									  <form>
										<div class="input-group">
										  <input type="text" class="form-control" placeholder="location">
										  <span class="input-group-btn">
											<button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> </button>
										  </span>
										</div>
									  </form>
									</li>

								  </ul>
								</li>
							  </ul>
							  <ul class="nav navbar-nav navbar-right">
								<li><a href="#"><img src="/assets/nav_button_download.png" <="" a=""></a></li><a href="#">
							  </a></ul>
							</div><!-- /.navbar-collapse -->
					</nav>
				</div>
		</div>
	</header>
	<section id="hometop">
			<div class="top_sec_inner">
				<img src="/assets/hero.png" alt="slider image" class="hero_img"/>
				<div class="hero_txt_outr">
						<h2 class="slider_title"> What do you <em>really</em> feel like? </h2>
						<div class="search_outr">
							<div class="input-group">
							  <input type="text" class="form-control" placeholder="Chips and burgers">
							  <span class="input-group-btn">
								<button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span><%= link_to "Search", result_path %></button>
							  </span>
							</div>
						</div>
				</div>
				</div>
	</section>
	<section id="slider_btm">
		<div class="container">
			<div class="row">
							<div class="col-lg-2 col-md-2 col-sm-4 col-xs-6">
				<a href="#">
				  <img src="/assets/image.png" class="img-responsive img-category" alt="Responsive image">
				  <span class="category">Halal Snack Pack</span>
				</a>
          </div>
          <div class="col-lg-2 col-md-2 col-sm-4 col-xs-6">
			<a href="#">
              <img src="/assets/image.png" class="img-responsive" alt="Responsive image">
              <span class="category">Fried Chicken</span>
            </a>
          </div>
          <div class="col-lg-2 col-md-2 col-sm-4 col-xs-6">
            <a href="#">
              <img src="/assets/image.png" class="img-responsive" alt="Responsive image">
              <span class="category">Burger</span>
            </a>
          </div>
          <div class="col-lg-2 col-md-2 col-sm-4 col-xs-6">
            <a href="#">
              <img src="/assets/image.png" class="img-responsive" alt="Responsive image">
              <span class="category">Sushi</span>
            </a>
          </div>
          <div class="col-lg-2 col-md-2 col-sm-4 col-xs-6">
            <a href="#">
              <img src="/assets/image.png" class="img-responsive" alt="Responsive image">
              <span class="category">Kebabs</span>
            </a>
          </div>
          <div class="col-lg-2 col-md-2 col-sm-4 col-xs-6">
            <a href="#">
              <img src="/assets/image.png" class="img-responsive" alt="Responsive image">
              <span class="category">Pasta</span>
            </a>
          </div>
        </div>
			</div>
		</div>
	</section>
	<section id="top_dishes">
		<div class="container">
			<div class="row">
				<h2 class="sec_title">MELBOURNE'S TOP RATED DISHES</h2>

					<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 hover_outr">
						<figure class="effect-lily">
							<div class="dish_top">
							<img src="/assets/1.png" alt="img12" class="dish_bk_img"/>
							<div class="dish_overlay"></div>
							<div class="rating">
										<img src="/assets/HEART.png" />
										<span>95<span>%</span></span>
									</div>
							<figcaption>
								<div>
									<h2>Dough cookies</h2>
									<p>Madam Chocolate <span class="rst_price">$15</span></p>
								</div>
							</figcaption>
							</div>
							<div class="dish_btm">
								<ul>
									<li> Now open</li>
									<li><a href="#">24 Victoria Street</a></li>
								</ul>
							</div>
						</figure>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 hover_outr">
						<figure class="effect-lily">
							<div class="dish_top">
							<img src="/assets/2.png" alt="img12" class="dish_bk_img"/>
							<div class="dish_overlay"></div>
							<div class="rating">
										<img src="/assets/HEART.png" />
										<span>95<span>%</span></span>
									</div>
							<figcaption>
								<div>
									<h2>Dough cookies</h2>
									<p>Madam Chocolate <span class="rst_price">$15</span></p>
								</div>
							</figcaption>
							</div>
							<div class="dish_btm">
								<ul>
									<li> Now open</li>
									<li><a href="#">24 Victoria Street</a></li>
								</ul>
							</div>
						</figure>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 hover_outr">
						<figure class="effect-lily">
							<div class="dish_top">
							<img src="/assets/3.png" alt="img12" class="dish_bk_img"/>
							<div class="dish_overlay"></div>
							<div class="rating">
										<img src="/assets/HEART.png" />
										<span>95<span>%</span></span>
									</div>
							<figcaption>
								<div>
									<h2>Dough cookies</h2>
									<p>Madam Chocolate <span class="rst_price">$15</span></p>
								</div>
							</figcaption>
							</div>
							<div class="dish_btm">
								<ul>
									<li> Now open</li>
									<li><a href="#">24 Victoria Street</a></li>
								</ul>
							</div>
						</figure>
					</div>

					<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 hover_outr">
						<figure class="effect-lily">
							<div class="dish_top">
							<img src="/assets/4.png" alt="img12" class="dish_bk_img"/>
							<div class="dish_overlay"></div>
							<div class="rating">
										<img src="/assets/HEART.png" />
										<span>95<span>%</span></span>
									</div>
							<figcaption>
								<div>
									<h2>Dough cookies</h2>
									<p>Madam Chocolate <span class="rst_price">$15</span></p>
								</div>
							</figcaption>
							</div>
							<div class="dish_btm">
								<ul>
									<li> Now open</li>
									<li><a href="#">24 Victoria Street</a></li>
								</ul>
							</div>
						</figure>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 hover_outr">
						<figure class="effect-lily">
							<div class="dish_top">
							<img src="/assets/5.png" alt="img12" class="dish_bk_img"/>
							<div class="dish_overlay"></div>
							<div class="rating">
										<img src="/assets/HEART.png" />
										<span>95<span>%</span></span>
									</div>
							<figcaption>
								<div>
									<h2>Dough cookies</h2>
									<p>Madam Chocolate <span class="rst_price">$15</span></p>
								</div>
							</figcaption>
							</div>
							<div class="dish_btm">
								<ul>
									<li> Now open</li>
									<li><a href="#">24 Victoria Street</a></li>
								</ul>
							</div>
						</figure>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 hover_outr">
						<figure class="effect-lily">
							<div class="dish_top">
							<img src= "/assets/1.png" alt="img12" class="dish_bk_img"/>
							<div class="dish_overlay"></div>
							<div class="rating">
										<img src="/assets/HEART.png" />
										<span>95<span>%</span></span>
									</div>
							<figcaption>
								<div>
									<h2>Dough cookies</h2>
									<p>Madam Chocolate <span class="rst_price">$15</span></p>
								</div>
							</figcaption>
							</div>
							<div class="dish_btm">
								<ul>
									<li> Now open</li>
									<li><a href="#">24 Victoria Street</a></li>
								</ul>
							</div>
						</figure>
					</div>




			</div>
			<div class="btn_outer">
				<a href="#">see more food</a>
				</div>
		</div>
	</section>
	<footer id="footr">
          <div class="container">
            <div class="row">
              <div class="col-lg-4 col-md-4 pull-right col-xs-12">
                <img src="/assets/phone.png" class="phone_img">
              </div>
			  <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <h2 class="footr_txt"> Do more with the app. Download it today!</h2>
                <ul>
					<li><a href="#"><img src="/assets/button_google_download.png"></a></li>
					<li><a href="#" class="appbutton"><img src="/assets/button_apple_download.png"></a></li>
				</ul>
              </div>

            </div>
          </div>
        </footer>

<script src="js/jquery-1.11.3.js" type="text/javascript" ></script>
<script src="js/custom_js.js" type="text/javascript"></script>
<script src="js/bootstrap.min.js" type="text/javascript" ></script>

<!--footer -->


</body>
</html>

app/views/pages/restaurant.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>Peppa Web</title>
<link href="css/bootstrap.min.css"  type="text/css" rel="stylesheet"/>
<link href="css/bootstrap-theme.min.css" type="text/css" rel="stylesheet" />
<link href="css/bootstrap-theme.min.css.map" type="text/css" rel="stylesheet" />
<link href="css/style.css"  type="text/css" rel="stylesheet"/>
</head>
<body>
	<header id="headr">
		<div class="container-fluid">
			<div class="row">
					<nav class="navbar navbar-default navbar-static-top">
						<div class="navbar-header">
						  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						  </button>
						  <a class="navbar-brand" href="#"><img src="/assets/logo.png"></a>
						</div>
							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							  <ul class="nav navbar-nav left_nav">
								<li class="dropdown">
								  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Collingwood, VIC <span class="caret"></span></a>
								  <ul class="dropdown-menu">
									<li>
									  <form>
										<div class="input-group">
										  <input type="text" class="form-control" placeholder="location">
										  <span class="input-group-btn">
											<button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> </button>
										  </span>
										</div>
									  </form>
									</li>

								  </ul>
								</li>
							  </ul>
							  <ul class="nav navbar-nav navbar-right">
								<li><a href="#"><img src="/assets/nav_button_download.png" <="" a=""></a></li><a href="#">
							  </a></ul>
							</div><!-- /.navbar-collapse -->
					</nav>
				</div>
		</div>
	</header>
	<section id="rasturantS">
		<div class="container-fluid">
			<div class="row">
				<div class=" col-lg-3 col-md-3 col-sm-12 col-xs-12 no_padding_left no_padding_right">
					<div class="restra_inner">
							<div class="restra_img_outr"><img src="/assets/6.png" alt="restra" /></div>
						<h2 class="restra_title">Easy Tiger</h2>
						<p class="restra-txt">24 Victoria street<br>collingwood, melbourne.</p>
						<a href="tel:0411409293" class="rstra_phn">0411 409 293</a>
					</div>

				</div>
				<div class=" col-lg-9 col-md-9 col-sm-12 col-xs-12 no_padding_right no_padding_left">
					<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 hover_outr no_padding_left no_padding_right">
						<figure class="effect-lily">
							<div class="dish_top">
							<img src="/assets/1.png" alt="img12" class="dish_bk_img"/>
							<div class="dish_overlay"></div>
							<div class="rating">
										<img src="/assets/HEART.png" />
										<span>95<span>%</span></span>
									</div>
							<figcaption>
								<div>
									<h2>Dough cookies</h2>
									<p>Madam Chocolate <span class="rst_price">$15</span></p>
								</div>
							</figcaption>
							</div>
						</figure>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 hover_outr no_padding_left no_padding_right">
						<figure class="effect-lily">
							<div class="dish_top">
							<img src="/assets/2.png" alt="img12" class="dish_bk_img"/>
							<div class="dish_overlay"></div>
							<div class="rating">
										<img src="/assets/HEART.png" />
										<span>95<span>%</span></span>
									</div>
							<figcaption>
								<div>
									<h2>Dough cookies</h2>
									<p>Madam Chocolate <span class="rst_price">$15</span></p>
								</div>
							</figcaption>
							</div>
						</figure>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 hover_outr no_padding_left no_padding_right">
						<figure class="effect-lily">
							<div class="dish_top">
							<img src="/assets/3.png" alt="img12" class="dish_bk_img"/>
							<div class="dish_overlay"></div>
							<div class="rating">
										<img src="/assets/HEART.png" />
										<span>95<span>%</span></span>
									</div>
							<figcaption>
								<div>
									<h2>Dough cookies</h2>
									<p>Madam Chocolate <span class="rst_price">$15</span></p>
								</div>
							</figcaption>
							</div>
							</figure>
					</div>

					<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 hover_outr no_padding_left no_padding_right">
						<figure class="effect-lily">
							<div class="dish_top">
							<img src="/assets/4.png" alt="img12" class="dish_bk_img"/>
							<div class="dish_overlay"></div>
							<div class="rating">
										<img src="/assets/HEART.png" />
										<span>95<span>%</span></span>
									</div>
							<figcaption>
								<div>
									<h2>Dough cookies</h2>
									<p>Madam Chocolate <span class="rst_price">$15</span></p>
								</div>
							</figcaption>
							</div>
						</figure>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 hover_outr no_padding_left no_padding_right">
						<figure class="effect-lily">
							<div class="dish_top">
							<img src="/assets/5.png" alt="img12" class="dish_bk_img"/>
							<div class="dish_overlay"></div>
							<div class="rating">
										<img src="/assets/HEART.png" />
										<span>95<span>%</span></span>
									</div>
							<figcaption>
								<div>
									<h2>Dough cookies</h2>
									<p>Madam Chocolate <span class="rst_price">$15</span></p>
								</div>
							</figcaption>
							</div>
							</figure>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 hover_outr no_padding_left no_padding_right">
						<figure class="effect-lily">
							<div class="dish_top">
							<img src="/assets/1.png" alt="img12" class="dish_bk_img"/>
							<div class="dish_overlay"></div>
							<div class="rating">
										<img src="/assets/HEART.png" />
										<span>95<span>%</span></span>
									</div>
							<figcaption>
								<div>
									<h2>Dough cookies</h2>
									<p>Madam Chocolate <span class="rst_price">$15</span></p>
								</div>
							</figcaption>
							</div>
							</figure>
					</div>


				</div>

			</div>
		</div>
	</section>
	<!--<footer id="footr">
          <div class="container">
            <div class="row">
              <div class="col-lg-4 col-md-4 pull-right">
                <img src="/assets/phone.png" class="phone_img">
              </div>
			  <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <h2 class="footr_txt"> Do more with the app. Download it today!</h2>
                <ul>
					<li><a href="#"><img src="/assets/button_google_download.png"></a></li>
					<li><a href="#" class="appbutton"><img src="/assets/button_apple_download.png"></a></li>
				</ul>
              </div>

            </div>
          </div>
        </footer>-->

<script src="js/jquery-1.11.3.js" type="text/javascript" ></script>
<script src="js/custom_js.js" type="text/javascript"></script>
<script src="js/bootstrap.min.js" type="text/javascript" ></script>
<!--footer -->
</body>
</html>